name = "oopqpqpsos6"
main = "worker.js"
compatibility_date = "2026-06-06"

kv_namespaces = [
  { binding = "DB", id = "b1f78a44d2f94cc28ccd0007a65144e2" }
]

[vars]
BOT_TOKEN = "8925497603:AAE_9ONjhp7KzJgbyELPYmmcfHAScMky8NA"
